GH-10261: Don't use Jackson 3 API in places with Jackson 2
Fixes: https://github.com/spring-projects/spring-integration/issues/10261

The problem is like this:
```
Caused by: java.lang.NoClassDefFoundError: tools/jackson/databind/ValueSerializer
    at org.springframework.integration.kafka.inbound.KafkaMessageDrivenChannelAdapter.<init>(KafkaMessageDrivenChannelAdapter.java:141)
```

Not clear why accessing static constant without any references to Jackson API causes imports of that class to be accessed,
but that is what we have so far.

* Use already deprecated `JacksonJsonUtils` in those places when `JacksonPresent.isJackson2Present()`