GH-10876: Fix `TcpNioConnection.convert()` for NPE
Fixes: https://github.com/spring-projects/spring-integration/issues/10876

The problem, essentially, is like this:

```
java.lang.NullPointerException: Cannot invoke "java.util.concurrent.CountDownLatch.await(long, java.util.concurrent.TimeUnit)" because "this.writingLatch" is null
	at org.springframework.integration.ip.tcp.connection.TcpNioConnection.convert(TcpNioConnection.java:380)
```
It happens because we don't create fresh (abandoned) `CountDownLatch` in the `ChannelInputStream.write()`
as the result of the https://github.com/spring-projects/spring-integration/issues/10671 fix.
However, the NPE check in the `TcpNioConnection.convert()` was not back-ported to `6.5.x`